# Generated by Django 3.0 on 2021-12-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211231_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='active_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='active_group'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(blank=True, max_length=60, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address_line2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='address_line2'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=60, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='state',
            field=models.CharField(blank=True, max_length=10, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='zip',
            field=models.CharField(blank=True, max_length=30, verbose_name='zip'),
        ),
    ]
