# Generated by Django 3.0 on 2022-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220120_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_accounting',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_developer',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_help_desk',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_manager',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_marketing',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_sales',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_security',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_social_media',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='alerts_web_monitor',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ip_address',
            field=models.CharField(blank=True, max_length=60, verbose_name='ip_address'),
        ),
    ]
