# Generated by Django 3.0 on 2022-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220303_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ci_list',
            field=models.BooleanField(default=True, null=True, verbose_name='ticket_list'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='department',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Exempt', 'Exempt'), ('Part Time', 'Part Time'), ('Contractor', 'Contractor'), ('Terminated', 'Terminated')], max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ticket_list',
            field=models.BooleanField(default=True, null=True, verbose_name='ticket_list'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_number',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='user_number'),
        ),
    ]
