# Generated by Django 3.0 on 2022-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220701_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='appraisal_date',
            new_name='termination_date',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='accrude_sick',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='accrude_sick'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_address',
            field=models.CharField(blank=True, max_length=60, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_address_line2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='address_line2'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_cell_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='personal_phone'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_city',
            field=models.CharField(blank=True, max_length=60, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_state',
            field=models.CharField(blank=True, max_length=10, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_zip',
            field=models.CharField(blank=True, max_length=30, verbose_name='zip'),
        ),
    ]
