# Generated by Django 3.0 on 2022-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220706_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='department',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='department'),
        ),
    ]
