# Generated by Django 3.0 on 2022-07-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofileinfo_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_address',
            field=models.CharField(blank=True, max_length=60, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact_relationship'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact_relationship'),
        ),
    ]
