# Generated by Django 3.0 on 2022-07-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220706_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_address_line2',
            field=models.CharField(blank=True, max_length=60, verbose_name='contact_address_line2'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_cell_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact_cell_phone'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_city',
            field=models.CharField(blank=True, max_length=60, verbose_name='contact_city'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact_email'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_personal_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact_personal_email'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact_phone'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_zip',
            field=models.CharField(blank=True, max_length=30, verbose_name='contact_zip'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='contact_address',
            field=models.CharField(blank=True, max_length=60, verbose_name='contact_address'),
        ),
    ]
