# Generated by Django 3.0 on 2022-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220706_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='appraisal_date',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_number',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='department_code',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='department_code'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='employee_number',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='employee_number'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='last_review_date'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='termination_date'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='ci_list',
            field=models.BooleanField(default=True, null=True, verbose_name='ci_list'),
        ),
    ]
