# Generated by Django 3.0 on 2022-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220706_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='reports_to',
            field=models.CharField(blank=True, max_length=50, verbose_name='active_group'),
        ),
    ]
