# Generated by Django 3.0 on 2022-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_userprofileinfo_contact_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='paychex',
            field=models.BooleanField(default=True, null=True, verbose_name='paychex'),
        ),
    ]
