# Generated by Django 3.0 on 2022-07-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_userprofileinfo_contact_state'),
        ('users', '0011_auto_20220706_0943'),
    ]

    operations = [
    ]
