# Generated by Django 3.0 on 2022-07-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userprofileinfo_paychex'),
        ('users', '0026_merge_20220707_1216'),
    ]

    operations = [
    ]
