# Generated by Django 3.0 on 2022-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userprofileinfo_paychex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='hours',
            field=models.DecimalField(blank=True, db_column='hours', decimal_places=8, max_digits=18, null=True),
        ),
    ]
