# Generated by Django 3.0 on 2022-07-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userprofileinfo_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='shift',
            field=models.IntegerField(blank=True, db_column='shift ', null=True),
        ),
    ]
