# Generated by Django 3.0 on 2022-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_merge_20220708_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_number',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='ci_list',
            field=models.BooleanField(default=True, null=True, verbose_name='ci_list'),
        ),
    ]
