# Generated by Django 3.0 on 2022-07-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userprofileinfo_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='hours',
            field=models.DecimalField(blank=True, db_column='hours', decimal_places=8, default=40, max_digits=18, null=True),
        ),
    ]
