# Generated by Django 3.0 on 2022-07-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20220713_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(default=1, verbose_name='year')),
                ('per_month', models.DecimalField(db_column='per_month', decimal_places=2, default=7.33, max_digits=6)),
                ('max', models.IntegerField(default=1, verbose_name='max')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='date_modified')),
            ],
        ),
    ]
