# Generated by Django 3.0 on 2022-07-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_pto'),
        ('users', '0028_auto_20220712_1630'),
    ]

    operations = [
    ]
