# Generated by Django 3.0 on 2022-07-18 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0038_auto_20220717_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptoaccruals',
            name='month',
        ),
        migrations.CreateModel(
            name='PTOAccrualsTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2014, verbose_name='year')),
                ('month', models.IntegerField(default=1, verbose_name='month')),
                ('holiday', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='holiday')),
                ('vacation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='vacation')),
                ('personal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='personal')),
                ('unpaid_pto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='unpaid_pto')),
                ('disability', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='disability')),
                ('family_leave', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='family_leave')),
                ('bereavement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='bereavement')),
                ('military', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='military')),
                ('voting_leave', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='voting_leave')),
                ('jury_duty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='jury_duty')),
                ('other', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='other')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
