# Generated by Django 3.0 on 2022-07-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_merge_20220713_1709'),
        ('users', '0039_auto_20220717_2053'),
    ]

    operations = [
    ]
