# Generated by Django 3.0 on 2022-07-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20220728_1333'),
        ('users', '0040_merge_20220719_0844'),
    ]

    operations = [
    ]
