# Generated by Django 3.0 on 2022-08-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_merge_20220728_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptoaccruals',
            name='week',
            field=models.IntegerField(default=1, verbose_name='week'),
        ),
    ]
