# Generated by Django 3.0 on 2022-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20220804_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptoaccrualstotal',
            name='pto_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='pto_adjustment'),
        ),
    ]
