# Generated by Django 3.0 on 2022-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_ptoaccrualstotal_pto_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptoaccrualstotal',
            name='pto_adjustment',
        ),
        migrations.AddField(
            model_name='ptoaccruals',
            name='pto_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='pto_adjustment'),
        ),
    ]
