# Generated by Django 3.0 on 2022-08-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20220804_0800'),
        ('users', '0042_auto_20220803_1603'),
    ]

    operations = [
    ]
