# Generated by Django 3.0 on 2022-10-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20221026_1139'),
        ('users', '0043_merge_20220810_0857'),
    ]

    operations = [
    ]
