# Generated by Django 3.0 on 2023-03-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_merge_20221026_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Exempt', 'Exempt'), ('Part Time', 'Part Time'), ('Temp', 'Temp'), ('Contractor', 'Contractor'), ('Terminated', 'Terminated')], max_length=50, verbose_name='status'),
        ),
    ]
