# Generated by Django 3.0 on 2023-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20230327_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='lean_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='lean_status'),
        ),
    ]
