# Generated by Django 3.0 on 2023-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_userprofileinfo_lean_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='lean_status',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Black', 'Black')], max_length=30, verbose_name='lean_status'),
        ),
    ]
