# Generated by Django 3.0 on 2023-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20230501_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='lean_status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('White', 'White'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Black', 'Black')], default='None', max_length=30, verbose_name='lean_status'),
        ),
    ]
