# Generated by Django 3.0 on 2023-05-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20230501_0809'),
        ('users', '0045_auto_20230407_1601'),
    ]

    operations = [
    ]
