# Generated by Django 3.0 on 2023-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20230501_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='gemba_team',
            field=models.BooleanField(default=True, null=True, verbose_name='gemba_team'),
        ),
    ]
