# Generated by Django 3.0 on 2023-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_userprofileinfo_gemba_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gemba_team',
            field=models.BooleanField(default=False, null=True, verbose_name='gemba_team'),
        ),
    ]
