# Generated by Django 3.0 on 2023-07-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_merge_20230501_0902'),
        ('users', '0050_auto_20230705_1200'),
    ]

    operations = [
    ]
