from django.contrib import admin
from .models import Sales_BOM, Sales_ChargeCodes, Sales_ClassCodes, Sales_ColorCodes, Sales_SizeCodes, Sales_TypeCodes, Sales_CompanyInfo, Sales_Customers, Sales_Expenses, Sales_Images, Sales_Inventory, Sales_Invoice, Sales_InvoiceID, Sales_Materials, Sales_Orders, Sales_PO, Sales_POID, Sales_Quote, Sales_QuoteID, Sales_SalesTransation, Sales_Vendors, Sales_ZipCode

admin.site.register(Sales_BOM)
admin.site.register(Sales_ChargeCodes)
admin.site.register(Sales_ClassCodes)
admin.site.register(Sales_ColorCodes)
admin.site.register(Sales_TypeCodes)
admin.site.register(Sales_CompanyInfo)
admin.site.register(Sales_Customers)
admin.site.register(Sales_Expenses)
admin.site.register(Sales_Images)
admin.site.register(Sales_Inventory)
admin.site.register(Sales_Invoice)
admin.site.register(Sales_InvoiceID)
admin.site.register(Sales_Orders)
admin.site.register(Sales_PO)
admin.site.register(Sales_POID)
admin.site.register(Sales_Materials)
admin.site.register(Sales_Quote)
admin.site.register(Sales_QuoteID)
admin.site.register(Sales_SalesTransation)
admin.site.register(Sales_Vendors)
admin.site.register(Sales_ZipCode)