# Generated by Django 2.1.15 on 2020-10-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20201005_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retail_inventory',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='CustomerType',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='ItemCharge',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='ItemDiscount',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='LocalSalesTax',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='MarkupPercent',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='ProfitabilityScale',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='Returns',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='SaleDate',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='SalesAssociateID',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='ShippingCharge',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='ShopifyTransation',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='TaxID',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='TotalDiscount',
        ),
        migrations.RemoveField(
            model_name='retail_inventory',
            name='TransationID',
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='Image',
            field=models.CharField(default='N/A', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='InStock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='InventoryClass',
            field=models.CharField(default='N/A', max_length=55, null=True, verbose_name='inventory class'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='InventoryColor',
            field=models.CharField(default='N/A', max_length=55, null=True, verbose_name='vendor id'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='InventoryNumber',
            field=models.CharField(default='N/A', max_length=55, null=True, verbose_name='inventory num'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='InventorySize',
            field=models.CharField(default='N/A', max_length=55, null=True, verbose_name='vendor id'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='InventorySizeDIM',
            field=models.CharField(default='N/A', max_length=55, null=True, verbose_name='inventory size'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='InventoryType',
            field=models.CharField(default='N/A', max_length=55, null=True, verbose_name='inventory type'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='Markup',
            field=models.FloatField(null=True, verbose_name='vendor id'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='NumberOrdered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='NumberSold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='RetailCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='retail cost'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='WholeSaleCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='wholesale cost'),
        ),
        migrations.AddField(
            model_name='retail_inventory',
            name='WholesaleMarkup',
            field=models.FloatField(null=True, verbose_name='vendor id'),
        ),
        migrations.AlterField(
            model_name='retail_inventory',
            name='Client',
            field=models.CharField(default='N/A', max_length=50, null=True, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='retail_inventory',
            name='InventoryID',
            field=models.CharField(default='N/A', max_length=55, null=True, verbose_name='inventory id'),
        ),
        migrations.AlterField(
            model_name='retail_inventory',
            name='ItemCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='item cost'),
        ),
        migrations.AlterField(
            model_name='retail_inventory',
            name='ItemDescription',
            field=models.CharField(default='N/A', max_length=255, null=True, verbose_name='item description'),
        ),
        migrations.AlterField(
            model_name='retail_inventory',
            name='ItemName',
            field=models.CharField(default='N/A', max_length=255, null=True, verbose_name='item name'),
        ),
    ]
