# Generated by Django 2.1.15 on 2020-10-04 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200919_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('address', models.CharField(default='N/A', max_length=100, verbose_name='address')),
                ('city', models.CharField(default='N/A', max_length=50, verbose_name='city')),
                ('state', models.CharField(default='N/A', max_length=25, verbose_name='state')),
                ('zip_code', models.CharField(default='N/A', max_length=25, verbose_name='zip_code')),
                ('phone', models.CharField(default='N/A', max_length=15, verbose_name='Phone')),
                ('email', models.CharField(default='N/A', max_length=50, verbose_name='email')),
                ('website', models.CharField(default='N/A', max_length=60, verbose_name='website')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='active')),
                ('image_file', models.CharField(max_length=50, null=True, verbose_name='image')),
                ('created_on', models.DateField()),
                ('last_entry', models.DateField()),
                ('inventory_id', models.IntegerField(null=True)),
                ('lat', models.FloatField(null=True, verbose_name='lat')),
                ('lng', models.FloatField(null=True, verbose_name='lng')),
                ('shelf', models.CharField(default='N/A', max_length=25, verbose_name='shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VendorID', models.CharField(default='N/A', max_length=50, null=True, verbose_name='vendor id')),
                ('MaterialType', models.CharField(default='N/A', max_length=255, null=True, verbose_name='material type')),
                ('Color', models.CharField(default='N/A', max_length=50, null=True, verbose_name='color')),
                ('Material', models.CharField(default='N/A', max_length=255, null=True, verbose_name='material')),
                ('MaterialSize', models.CharField(default='N/A', max_length=50, null=True, verbose_name='material size')),
                ('QuantityPrice', models.CharField(default='N/A', max_length=50, null=True, verbose_name='quantity price')),
                ('Cost', models.CharField(default='N/A', max_length=50, null=True, verbose_name='cost')),
                ('CostType', models.CharField(default='N/A', max_length=50, null=True, verbose_name='cost type')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='client')),
                ('Active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('ChargeID', models.CharField(default='N/A', max_length=50, null=True, verbose_name='charge id')),
                ('InvoiceID', models.CharField(default='N/A', max_length=255, null=True, verbose_name='invoice id')),
                ('CustomerID', models.CharField(default='N/A', max_length=50, null=True, verbose_name='customer id')),
                ('MaterialDate', models.DateField(null=True)),
                ('last_update', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='N/A', max_length=100, verbose_name='description')),
                ('category', models.CharField(default='N/A', max_length=50, verbose_name='category')),
                ('band', models.CharField(default='N/A', max_length=50, verbose_name='band')),
                ('vendor', models.CharField(max_length=50, null=True, verbose_name='vendor')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('comments', models.CharField(max_length=200, null=True, verbose_name='comments')),
                ('image_file', models.CharField(max_length=20, null=True, verbose_name='Image_file')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='status')),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('inventory_id', models.IntegerField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
