# Generated by Django 3.0.8 on 2020-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='N/A', max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='N/A', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.CharField(default='N/A', max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image_file',
            field=models.CharField(max_length=50, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True, verbose_name='lat'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(null=True, verbose_name='lng'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default='N/A', max_length=25, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.CharField(default='N/A', max_length=60, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(default='N/A', max_length=25, verbose_name='zip_code'),
        ),
    ]
