# Generated by Django 3.0.8 on 2020-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200815_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='image_file',
            field=models.CharField(max_length=20, null=True, verbose_name='Image_file'),
        ),
    ]
