# Generated by Django 3.2.3 on 2021-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(default='N/A', max_length=50, null=True, verbose_name='serial number')),
                ('unit', models.CharField(default='N/A', max_length=10, null=True, verbose_name='modelname')),
                ('bins', models.CharField(default='N/A', max_length=100, null=True, verbose_name='locationname')),
                ('description', models.CharField(default='N/A', max_length=500, null=True, verbose_name='description')),
                ('vendor', models.CharField(default='N/A', max_length=100, null=True, verbose_name='locationname')),
                ('customer', models.CharField(default='N/A', max_length=100, null=True, verbose_name='locationname')),
                ('gl_code', models.IntegerField(null=True)),
                ('prod_code', models.CharField(default='N/A', max_length=100, null=True, verbose_name='shelf')),
                ('in_process', models.IntegerField(null=True)),
                ('on_order', models.IntegerField(null=True)),
                ('reserved', models.IntegerField(null=True)),
                ('outside', models.FloatField(null=True)),
                ('on_hand', models.IntegerField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('cost_total', models.FloatField(null=True)),
                ('timestamp', models.DateField()),
                ('update_by', models.CharField(default='N/A', max_length=50, verbose_name='update_by')),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
    ]
