# Generated by Django 3.0.8 on 2020-09-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bins',
            field=models.CharField(default='N/A', max_length=100, null=True, verbose_name='locationname'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='customer',
            field=models.CharField(default='N/A', max_length=100, null=True, verbose_name='locationname'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='N/A', max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(default='N/A', max_length=50, null=True, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='prod_code',
            field=models.CharField(default='N/A', max_length=100, null=True, verbose_name='shelf'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default='N/A', max_length=10, null=True, verbose_name='modelname'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vendor',
            field=models.CharField(default='N/A', max_length=100, null=True, verbose_name='locationname'),
        ),
    ]
