from django.contrib import admin
from .models import Retail_BOM, Retail_ChargeCodes, Retail_ClassCodes, Retail_ColorCodes, Retail_SizeCodes, Retail_TypeCodes, Retail_CompanyInfo, Retail_Customers, Retail_Expenses, Retail_Images, Retail_Inventory, Retail_Invoice, Retail_InvoiceID, Retail_Materials, Retail_Orders, Retail_PO, Retail_POID, Retail_Quote, Retail_QuoteID, Retail_SalesTransation, Retail_Vendors, Retail_ZipCode

admin.site.register(Retail_BOM)
admin.site.register(Retail_ChargeCodes)
admin.site.register(Retail_ClassCodes)
admin.site.register(Retail_ColorCodes)
admin.site.register(Retail_TypeCodes)
admin.site.register(Retail_CompanyInfo)
admin.site.register(Retail_Customers)
admin.site.register(Retail_Expenses)
admin.site.register(Retail_Images)
admin.site.register(Retail_Inventory)
admin.site.register(Retail_Invoice)
admin.site.register(Retail_InvoiceID)
admin.site.register(Retail_Orders)
admin.site.register(Retail_PO)
admin.site.register(Retail_POID)
admin.site.register(Retail_Materials)
admin.site.register(Retail_Quote)
admin.site.register(Retail_QuoteID)
admin.site.register(Retail_SalesTransation)
admin.site.register(Retail_Vendors)
admin.site.register(Retail_ZipCode)

