# Generated by Django 3.0 on 2021-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='active_group',
            field=models.CharField(default='N/A', max_length=50, null=True, verbose_name='active_group '),
        ),
    ]
