# Generated by Django 3.0 on 2021-12-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofileinfo_active_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='active_group',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address_line2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_accounting',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_accounting'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_developer',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_developer'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_help_desk',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_help_desk'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_manager',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_manager'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_marketing',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_marketing'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_sales',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_sales'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_security',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_security'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_social_media',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_social_media'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_web_monitor',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_web_monitor'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User'), (2, 'Supervisor'), (3, 'Manager'), (4, 'Owner'), (5, 'Engineer'), (6, 'Technician'), (7, 'Contractor'), (8, 'Developer'), (9, 'Marketing'), (10, 'Sales'), (11, 'Social_Media'), (12, 'Web_Monitor'), (13, 'Help_Desk'), (14, 'Security')], null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='zip',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
