# Generated by Django 3.0 on 2022-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220228_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='hourly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='hourly'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='salaried',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='salaried'),
        ),
    ]
