# Generated by Django 3.0 on 2022-03-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220301_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='hire_date'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='personal_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='personal_email'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='personal_phone'),
        ),
    ]
