# Generated by Django 3.0 on 2022-03-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220302_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='appraisal_date',
            field=models.DateField(blank=True, null=True, verbose_name='appraisal_date'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='review_date'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='wage_change_date',
            field=models.DateField(blank=True, null=True, verbose_name='wage_change_date'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('President', 'President'), ('Vice President', 'Vice President'), ('Controller', 'Controller'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Owner', 'Owner'), ('Engineer', 'Engineer'), ('Test_Engineer', 'Test_Engineer'), ('Software_Engineer', 'Software_Engineer'), ('Mechaical_Engineer', 'Mechaical_Engineer'), ('Technician', 'Technician'), ('Tester', 'Tester'), ('Prep_Operator', 'Prep_Operator'), ('Designer', 'Designer'), ('Draftsman', 'Draftsman'), ('Mechanical_Assembler', 'Mechanical_Assembler'), ('Electrical_Assembler', 'Electrical_Assembler'), ('Operator', 'Operator'), ('Contractor', 'Contractor'), ('Managed_Services_Provider', 'Managed_Services_Provider'), ('IT', 'IT'), ('Developer', 'Developer'), ('Marketing', 'Marketing'), ('Costing', 'Costing'), ('Sales', 'Sales'), ('Social_Media', 'Social_Media'), ('Web_Monitor', 'Web_Monitor'), ('Help_Desk', 'Help_Desk'), ('Security', 'Security')], max_length=50, null=True, verbose_name='role'),
        ),
    ]
