# Generated by Django 3.0 on 2022-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220303_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='accrude_vac',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='salaried'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='reports_to',
            field=models.CharField(blank=True, max_length=50, verbose_name='reports_to'),
        ),
    ]
