# Generated by Django 3.0 on 2022-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220701_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='termination_date',
            new_name='appraisal_date',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='accrude_sick',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='accrude_vac',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_cell_phone',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_city',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_state',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='contact_zip',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='reports_to',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ci_list',
            field=models.BooleanField(default=True, null=True, verbose_name='ticket_list'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Exempt', 'Exempt'), ('Part Time', 'Part Time'), ('Contractor', 'Contractor')], max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ticket_list',
            field=models.BooleanField(default=True, null=True, verbose_name='ticket_list'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='department',
            field=models.IntegerField(default=0, verbose_name='departmen'),
        ),
    ]
