# Generated by Django 3.0 on 2022-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220706_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Exempt', 'Exempt'), ('Part Time', 'Part Time'), ('Contractor', 'Contractor'), ('Terminated', 'Terminated')], max_length=50, verbose_name='status'),
        ),
    ]
