# Generated by Django 3.0 on 2022-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220706_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='department',
            field=models.IntegerField(default=0, verbose_name='department'),
        ),
    ]
