# Generated by Django 3.0 on 2022-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220706_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_number',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='user_number'),
        ),
    ]
