# Generated by Django 3.0 on 2022-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userprofileinfo_last_training_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_user', models.CharField(db_column='last_user', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='reports_to',
            field=models.CharField(blank=True, max_length=50, verbose_name='reports_to'),
        ),
    ]
