# Generated by Django 3.0 on 2022-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220707_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='employee_code',
            field=models.CharField(blank=True, db_column='Employee_Code', max_length=20, null=True),
        ),
    ]
