# Generated by Django 3.0 on 2022-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userprofileinfo_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_state',
            field=models.CharField(blank=True, max_length=60, verbose_name='contact_state'),
        ),
    ]
