# Generated by Django 3.0 on 2022-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220713_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='shift_end',
            field=models.DateField(blank=True, null=True, verbose_name='shift_end '),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='shift_start',
            field=models.DateField(blank=True, null=True, verbose_name='shift_start'),
        ),
    ]
