# Generated by Django 3.0 on 2022-07-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220713_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='shift_end',
            field=models.TimeField(blank=True, null=True, verbose_name='shift_end '),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='shift_start',
            field=models.TimeField(blank=True, null=True, verbose_name='shift_start'),
        ),
    ]
