# Generated by Django 3.0 on 2022-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20220713_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='hours',
            field=models.DecimalField(db_column='hours', decimal_places=1, default=40, max_digits=4),
        ),
    ]
