# Generated by Django 3.0 on 2022-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20220714_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptoaccruals',
            name='week_updated',
        ),
        migrations.AddField(
            model_name='ptoaccruals',
            name='month',
            field=models.IntegerField(default=1, verbose_name='month'),
        ),
    ]
