# Generated by Django 3.0 on 2022-07-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20220715_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptoaccruals',
            name='paid_pto',
        ),
        migrations.AddField(
            model_name='ptoaccruals',
            name='personal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='personal'),
        ),
    ]
