# Generated by Django 3.0 on 2022-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20220717_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptoaccruals',
            name='month',
            field=models.IntegerField(default=1, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='ptoaccruals',
            name='week',
            field=models.IntegerField(default=1, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='ptoaccruals',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True, verbose_name='weekday'),
        ),
        migrations.AddField(
            model_name='ptoaccrualstotal',
            name='week',
            field=models.IntegerField(default=1, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='ptoaccrualstotal',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True, verbose_name='weekday'),
        ),
    ]
