# Generated by Django 3.0 on 2022-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20220728_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptoaccruals',
            name='week',
            field=models.IntegerField(default=1, verbose_name='week'),
        ),
    ]
