# Generated by Django 3.0.8 on 2020-08-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200801_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
    ]
