# Generated by Django 3.0.8 on 2020-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200803_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='band',
            field=models.CharField(default='N/A', max_length=29, verbose_name='band'),
        ),
        migrations.AlterField(
            model_name='model',
            name='category',
            field=models.CharField(default='N/A', max_length=20, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.CharField(default='N/A', max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='model',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.CharField(max_length=50, null=True, verbose_name='vendor'),
        ),
    ]
