# Generated by Django 3.0.8 on 2020-08-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20200816_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image_folder/'),
        ),
    ]
