# Generated by Django 3.0.8 on 2020-08-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_model_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
    ]
