# Generated by Django 3.0.8 on 2020-08-28 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20200828_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 13, 30, 45, 61084, tzinfo=utc)),
        ),
    ]
