# Generated by Django 3.0.8 on 2020-08-28 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20200828_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='inventory_id',
        ),
        migrations.AlterField(
            model_name='model',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 16, 49, 13, 617891, tzinfo=utc)),
        ),
    ]
