# Generated by Django 3.0.8 on 2020-08-28 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200818_2117'),
        ('equipment', '0010_auto_20200828_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='inventory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory'),
        ),
        migrations.AlterField(
            model_name='model',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 16, 51, 45, 324232, tzinfo=utc)),
        ),
    ]
