# Generated by Django 3.0.8 on 2020-08-29 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_auto_20200828_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='band',
            field=models.CharField(default='N/A', max_length=50, verbose_name='band'),
        ),
        migrations.AlterField(
            model_name='model',
            name='category',
            field=models.CharField(default='N/A', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='model',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 13, 23, 5, 833981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='model',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='status'),
        ),
    ]
