# Generated by Django 3.0.8 on 2020-08-29 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_auto_20200829_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 15, 0, 55, 151608, tzinfo=utc)),
        ),
    ]
