# Generated by Django 3.0.8 on 2020-08-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20200801_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(default='N/A', max_length=25, verbose_name='location state'),
        ),
    ]
